"""fix company_name

Revision ID: 18385e870af7
Revises: da6ee3725c11
Create Date: 2025-08-06 16:40:35.625939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18385e870af7'
down_revision: Union[str, Sequence[str], None] = 'da6ee3725c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_name', sa.String(length=150), nullable=True))
    op.drop_index(op.f('ix_company_compagny_name'), table_name='company')
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    op.drop_column('company', 'compagny_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('compagny_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.create_index(op.f('ix_company_compagny_name'), 'company', ['compagny_name'], unique=False)
    op.drop_column('company', 'company_name')
    # ### end Alembic commands ###
