"""fist_migration

Revision ID: 64f446684bc6
Revises: 
Create Date: 2025-08-06 00:57:07.219162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f446684bc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('bp', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adresse_id'), 'adresse', ['id'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('type_of_file', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compagny_name', sa.String(length=150), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_compagny_name'), 'company', ['compagny_name'], unique=False)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('share_holders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_holders_first_name'), 'share_holders', ['first_name'], unique=False)
    op.create_index(op.f('ix_share_holders_id'), 'share_holders', ['id'], unique=False)
    op.create_index(op.f('ix_share_holders_last_name'), 'share_holders', ['last_name'], unique=False)
    op.create_index(op.f('ix_share_holders_phone_number'), 'share_holders', ['phone_number'], unique=False)
    op.create_table('participation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_holder_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('total_share', sa.Integer(), nullable=True),
    sa.Column('percentage_on_capital', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['share_holder_id'], ['share_holders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participation_id'), 'participation', ['id'], unique=False)
    op.create_table('share_insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('number_of_share', sa.Integer(), nullable=True),
    sa.Column('type_action', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_insurance_id'), 'share_insurance', ['id'], unique=False)
    op.create_table('attribution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_insurance_id', sa.Integer(), nullable=True),
    sa.Column('share_holder_id', sa.Integer(), nullable=True),
    sa.Column('emission_certificate_file_id', sa.Integer(), nullable=True),
    sa.Column('number_of_share', sa.Integer(), nullable=True),
    sa.Column('attribution_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emission_certificate_file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['share_holder_id'], ['share_holders.id'], ),
    sa.ForeignKeyConstraint(['share_insurance_id'], ['share_insurance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_id'), 'attribution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribution_id'), table_name='attribution')
    op.drop_table('attribution')
    op.drop_index(op.f('ix_share_insurance_id'), table_name='share_insurance')
    op.drop_table('share_insurance')
    op.drop_index(op.f('ix_participation_id'), table_name='participation')
    op.drop_table('participation')
    op.drop_index(op.f('ix_share_holders_phone_number'), table_name='share_holders')
    op.drop_index(op.f('ix_share_holders_last_name'), table_name='share_holders')
    op.drop_index(op.f('ix_share_holders_id'), table_name='share_holders')
    op.drop_index(op.f('ix_share_holders_first_name'), table_name='share_holders')
    op.drop_table('share_holders')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_compagny_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_adresse_id'), table_name='adresse')
    op.drop_table('adresse')
    # ### end Alembic commands ###
