"""fix user-shareholder relations

Revision ID: a04a2b57196f
Revises: 518b5d06d40f
Create Date: 2025-08-06 09:44:44.904323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04a2b57196f'
down_revision: Union[str, Sequence[str], None] = '518b5d06d40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_holders', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'share_holders', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_holders', type_='foreignkey')
    op.drop_column('share_holders', 'created_by_id')
    # ### end Alembic commands ###
